### ISSUE TITLE
Win32api ctrl_c call kills restart process

### ISSUE THREAD

**Issue by Billiam** [vais/restart#2]
The restart process itself is being killed in my environment when the win32api console control event is triggered:

```ruby
ctrl_c = Win32API.new('Kernel32', 'GenerateConsoleCtrlEvent', 'II', 'I')
...
ctrl_c.call(0, 0)
```

Commenting the call out allows the backup `process.kill` to be used instead, and then works as expected.

Not sure what the fix for this should be, or if it's unique to my environment (ruby under mingw32).

**Comment by vais** [comment]
Sorry for the delayed response, @Billiam. [This code](https://github.com/vais/restart/blob/master/lib/restart.rb#L144) is supposed to make sure that restart itself does not quit when Ctrl-C event is generated:
```ruby
trap('INT') do
  exit unless restarting || process.alive?
end
```
I've only ever used restart on Windows XP and Windows Server 2008 with Ruby 2.0.0, so it's natural that your mileage may vary. What version of Ruby/Windows do you have? Could you add some `puts` for debugging into the `trap` block to see if it executes?

**Comment by Billiam** [comment]
Hmm. I'm running ruby 2.1.6p336 under windows 7.

After a fresh ruby install, I was unable to get restart to install and run correctly without updating the listen dependency to '~> 3.0'. (related issue here: https://github.com/celluloid/celluloid/issues/619)

The `INT` trap isn't executing it looks like, after throwing some debugging statements around.

**Comment by vais** [comment]
@Billiam thanks so much for your help. I have bumped the listen dependency to `~> 3.0` and will be releasing a new version of the gem as soon as I figure out what's causing your original issue.

Could you please run `ruby -ve "p Signal.list"` on your system and share the output? Here's what I got:
```
C:\Documents and Settings\Administrator>ruby -ve "p Signal.list"
ruby 2.0.0p247 (2013-06-27) [i386-mingw32]
{"EXIT"=>0, "INT"=>2, "ILL"=>4, "ABRT"=>22, "FPE"=>8, "KILL"=>9, "SEGV"=>11, "TERM"=>15}
```
Perhaps on your system the `INT` signal is not registered somehow? I can't think of any other reason for the `trap('INT')` block to not be executing at all :confused:

**Comment by vais** [comment]
Also, please try changing `trap('INT')` to `trap(2)` and let me know if that makes a difference. Really appreciate your help on this, since I do not have access to a Win 7 machine to debug this issue myself...

**Comment by vais** [comment]
@Billiam one more idea to try: perhaps instead of `INT` your system is getting a `TERM`? In which case trying `trap('TERM')` or `trap(15)` would fix things? Thanks!

**Comment by Billiam** [comment]
@vais Here are my available signals:

```
$ ruby -ve "p Signal.list"
ruby 2.1.6p336 (2015-04-13 revision 50298) [i386-mingw32]
{"EXIT"=>0, "INT"=>2, "ILL"=>4, "ABRT"=>22, "FPE"=>8, "KILL"=>9, "SEGV"=>11, "TERM"=>15}
```

No change in behavior with `trap(2)`, `trap('TERM')`, or `trap(15)` though.

**Comment by vais** [comment]
Hmm... @Billiam would you mind maybe trying a simple isolated test to see if `trap('INT')` works by itself? Something like this:

``` ruby
#test.rb 
trap('INT') do
  p Time.now
end
sleep 10
```

Then:

```
$ ruby test.rb 
```

Then mash Ctrl-C a few times. Here's what I get on my Mac:

```
^C2015-09-03 20:44:00 +0700
^C2015-09-03 20:44:01 +0700
^C2015-09-03 20:44:02 +0700
^C2015-09-03 20:44:03 +0700
```

Thanks again!

**Comment by Billiam** [comment]
Under mingw / gitbash etc., it will quit back to a prompt. Occasionally, it will output the date one time but still exit.

In a standard windows command prompt, it works correctly, outputting the current time for each `^C`

**Comment by vais** [comment]
Thank you, @Billiam. So, this looks like mingw/gitbash issue then, not sure I'll be able to do anything about that in restart. I only use it with standard windows command prompt. Feel free to re-open this issue if you have any other ideas.

Once again, thanks for pointing out the issue with listen - I have released vesion 1.0.2 of restart that uses listen 3.0 sans celluloid and so installs cleanly.

**Comment by Billiam** [comment]
Understood. 

I've made a commit which is working for my use cases in mingw and the standard windows command prompt: 

https://github.com/Billiam/restart/tree/feature/mingw
https://github.com/Billiam/restart/commit/cf208d09e4dbe46cefaa110e2342367de2126d83

There are probably use cases that I'm not accounting for though. Any idea what these might be?

**Comment by vais** [comment]
Well, there's one important use case that you are accounting for in your commit message, which is _Removes process group killing in favor of int/kill on spawned process only._ No time to test this out now, but how does that affect running things like `bundle exec ...` and such? Basically, if the process you are running spawns other processes, I would like all of them dead - I'm afraid simply killing the original process does not accomplish that. If this works for you though, that's all that matters :wink:

**Comment by Billiam** [comment]
That makes sense. 

Is `Win32API.new('Kernel32', 'GenerateConsoleCtrlEvent', 'II', 'I')` able to kill the whole process tree, or does that create orphaned/zombie processes as well?

**Comment by vais** [comment]
@Billiam quoting from the `GenerateConsoleCtrlEvent` [docs](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683155%28v=vs.85%29.aspx):

> [GenerateConsoleCtrlEvent function] Sends a specified signal to a console process group that shares the console associated with the calling process.

So, yes, in a way it can be expected to kill the whole process tree, since each process sharing the console will receive Ctrl-C. For what it's worth, this technique has been working well for me so far :smile:
