### ISSUE TITLE
How target just a single file?

### ISSUE THREAD

**Issue by daBee** [vais/restart#3]
I'm not clear as to how to just target a single file.  

I have `~/app.rb` that I want to run in the terminal every time it is saved.  No subdirectories, nothing else.  Just that file.  From the docs it seems -i but the regex for "all subdirectory files" is unclear.  I'm also seeing `.rvm/` trigger the item.  

Any insight appreciated.  Cheers

**Comment by vais** [comment]
Have you tried `restart -f app.rb ruby app.rb`?

**Comment by daBee** [comment]
I've moved on with rbenv as opposed to RVM, so things are working with the other technology I've been using.  Cheers
